version: '2'
services:
    bis-app:
        image: bis
        external_links:
            - bis-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bis?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bis-mysql:
        extends:
            file: mysql.yml
            service: bis-mysql
